### ISSUE TITLE
status

### ISSUE THREAD

**Issue by iamstarkov** [Mikhail-Ivanyushin/DoTextOK#2]
is this project alive?

**Comment by Mikhail-Ivanyushin** [comment]
На GitHub уже нет. А в сообществе верстальщиков проект развивается. В апреле-мае будет очередное обновление. Доступ по подписке.
Информация тут:
https://youtu.be/czpleFsdb-E
и тут:
http://ivmi-adobeindesign.blogspot.ru/

23.04.2015, 12:31, "Vladimir Starkov" notifications@github.com:

**Comment by iamstarkov** [comment]
По второй ссылке пусто и нет никакой информации =(

**Comment by Mikhail-Ivanyushin** [comment]
Владимир, обе ссылки рабочие.Но если хотите, могу именно Вам прислать последний архив, а я включу Ваш e-mail в рассылку на smartresponder. (Если это там для меня возможно, еще не было такой задачи. Но архив я Вам отошлю)  Подписка интересна тем, что всё ещё идут обновления. 23.04.2015, 19:50, "Vladimir Starkov" notifications@github.com:По второй ссылке пусто и нет никакой информации =(
